### ISSUE TITLE
Braking  the build cargo build --release

### ISSUE THREAD

**Issue by aditya711983** [casper-ecosystem/hello-world#9] opened 2021-07-21 18:12 UTC
error: failed to parse manifest at `/home/aditya/.cargo/registry/src/github.com-1ecc6299db9ec823/zeroize-1.4.1/Cargo.toml`

Caused by:
  feature `resolver` is required

  consider adding `cargo-features = ["resolver"]` to the manifest

**Comment by aditya711983** [comment] 2021-07-22 04:20
@zie1ony @ramujin @stephenmoloney @darthsiroftardis 

Could you please guide ,why i am getting this error.

rustup --version
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.50.0-nightly (f76ecd066 2020-12-15)`

**Comment by ramujin** [comment] 2021-07-23 19:07
Hi @aditya711983, thank you for finding this bug! We are investigating it and will update as soon as we have a fix.

**Comment by mbrubeck** [comment] 2021-08-17 23:10
The problem is that the [`rust-toolchain`] file in this repository specifies an old nightly version of the Rust compiler, which is not compatible with the latest versions of some dependencies.  This could be fixed by updating the `rust-toolchain` file to specify a newer version of Rust (and making sure all the code is updated to work in that version), or by checking in a `Cargo.lock` file to pin the dependencies to versions that work with the older compiler.

[`rust-toolchain`]: https://github.com/casper-ecosystem/hello-world/blob/bea48a623f2aaeb67436f857a752ba09b8a1b5d7/rust-toolchain

**Comment by mbrubeck** [comment] 2021-08-17 23:15
There is a fix in #10.  For now, users can work around this issue by running this command to downgrade the `zeroize` dependency:

```
cargo update --package zeroize --precise 1.3.0
```

**Closed as completed** 2021-09-07 17:08 UTC
